version: "3.9"
services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TF_VAR_my_ip=${TF_VAR_my_ip}
      - TF_VAR_eip=${TF_VAR_eip}
      - TF_VAR_port_pma=${TF_VAR_port_pma}
      - TF_VAR_port_rds=${TF_VAR_port_rds}